### PR TITLE
Fix `if` with nullable inverse subscriptions

### LINKED ISSUE #97: Nullable relations are not checked when creating inverse subscriptions
For `OneToMany` or `OneToOne` relations, Purgatory automatically creates inverse subscriptions for related entities.
When an `#[PurgeOn]` includes an `if` condition, this condition is transformed to fit the inverse subscription context.

### Example
Given an `Author` entity with a OneToMany relation to `Post` (and `Post` may or may not have an `Author`)
```php
#[PurgeOn(Author::class,
    target: 'posts',
    if: 'obj.isActive()'
)]
```

Purgatory will automatically create subscription for `Post`, transforming the `if` condition to:
`'obj.getAuthor().isActive()'`

### Problem
If `getAuthor()` returns `null`, this results in an exception during the purge process:
`RuntimeException: Unable to call method "isActive()" of non-object "obj.getAuthor()".`

To handle this safely, the generated condition should include a null check before evaluating the rest of the expression.
For example, the transformed condition should become:
`obj.getAuthor() !== null && (obj.getAuthor().isActive())`

This ensures the purge logic only attempts to evaluate the method if the related entity exists, preventing runtime errors for optional relations.

### PR DESCRIPTION
**Pull request by Brajk19**
fixes https://github.com/sofascore/purgatory-bundle/issues/97

### CODE REVIEW

File: tests/Functional/TestApplication/Controller/PersonController.php [hunk 1]
```diff
@@ -122,6 +122,10 @@ public function personListForCountryAction(?Country $country = null)
     #[Route('/{id}/cars', 'person_cars_list')]
     #[AnnotationRoute('/{id}/cars', name: 'person_cars_list')]
     #[PurgeOn(Person::class, target: 'cars')]
+    #[PurgeOn(Person::class,
+        target: 'cars',
+        if: "obj.firstName === 'John'",
+    )]
     public function personCarsList(Person $person)
```
Comment (Brajk19) [inline tests/Functional/TestApplication/Controller/PersonController.php:129]: @HypeMC i did't add separate test because we already have one specifically for nullable inverse subscriptions:
https://github.com/sofascore/purgatory-bundle/blob/a14ef9bf4e195fa9cd609a92de538af07dc55897/tests/Application/ApplicationTest.php#L630-L654

it just didn't fail because the PurgeOn attribute did not have `if`.
this test fails for added PurgeOn without changes from PR

File: src/Cache/PropertyResolver/AssociationResolver.php [hunk 2]
```diff
@@ -73,7 +73,9 @@ public function resolveSubscription(
 
         if (null !== $if = $routeMetadata->purgeOn->if) {
             $expression = (string) $if;
-            $if = new Expression(str_replace('obj', 'obj.'.$this->createGetter($associationClass, $associationTarget), $expression));
+            $getter = $this->createGetter($associationClass, $associationTarget);
+            $inverseIf = str_replace('obj', 'obj.'.$this->createGetter($associationClass, $associationTarget), $expression);
```
Comment (HypeMC) [inline src/Cache/PropertyResolver/AssociationResolver.php:77]: @Brajk19 Should we search for `obj.` instead?

Comment (Brajk19) [reply src/Cache/PropertyResolver/AssociationResolver.php:77]: that wouldn't work if we have checks like `obj !== null` or custom EL functions: `foo(obj)` where there is no dot

**Review by HypeMC — APPROVED** [review]
